name: Deploy Image
on:
  push:
    branches: [ docker ]
jobs:
  package:
    name: Build image
    runs-on: ubuntu-latest
    env:
      PROJECT_ID: cei-data-science
      IMAGE_NAME: ce-ditto
      TAG: latest
    steps:
      - uses: actions/checkout@v2
      - uses: google-github-actions/setup-gcloud@v0
        with:
          service_account_key: ${{ secrets.SERVICE_ACCOUNT_KEY }}
          project_id: ${{ secrets.PROJECT_ID }}
          export_default_credentials: true
      - name: Check if docker is running
        run: systemctl status docker
      - name: Build Container
        run: |
          DOCKER_BUILDKIT=1 docker build  --secret id=gcp_credentials,src=$GOOGLE_APPLICATION_CREDENTIALS -t local_container .
      - name: Tag container
        run: docker tag local_container gcr.io/${{ env.PROJECT_ID }}/${{ env.IMAGE_NAME }}:${{ env.TAG }}
      - name: Push Image
        run: |
          gcloud auth configure-docker
          docker push gcr.io/${{ env.PROJECT_ID }}/${{ env.IMAGE_NAME }}:${{ env.TAG }}